// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID        int64
	AuthorID  uuid.UUID
	Title     string
	EmbedUrl  string
	Body      string
	CreatedAt time.Time
}

type User struct {
	ID         uuid.UUID
	Username   string
	Email      string
	PasswdHash string
	CreatedAt  time.Time
}
