// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        int64
	PostID    int64
	ParentID  *int64
	AuthorID  uuid.UUID
	Body      string
	CreatedAt time.Time
	DeletedAt *time.Time
}

type Post struct {
	ID        int64
	AuthorID  uuid.UUID
	Title     string
	EmbedUrl  string
	Body      string
	CreatedAt time.Time
	DeletedAt *time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	LastUsed  *time.Time
	RevokedAt *time.Time
}

type User struct {
	ID         uuid.UUID
	Username   string
	Email      string
	PasswdHash string
	CreatedAt  time.Time
	DeletedAt  *time.Time
}
