// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, username, email, passwd_hash, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswdHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, passwd_hash, created_at FROM users WHERE lower(username) = lower($1::text)
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswdHash,
		&i.CreatedAt,
	)
	return i, err
}

const newUser = `-- name: NewUser :one
INSERT INTO users
(id, username, email, passwd_hash, created_at)
VALUES (uuidv7(), $1, $2, $3, NOW())
RETURNING id, username, email, passwd_hash, created_at
`

type NewUserParams struct {
	Username   string
	Email      string
	PasswdHash string
}

func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) (User, error) {
	row := q.db.QueryRow(ctx, newUser, arg.Username, arg.Email, arg.PasswdHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswdHash,
		&i.CreatedAt,
	)
	return i, err
}
